ARG VER_NGX="1.29.3-alpine"

FROM --platform=$BUILDPLATFORM doocs/md:latest-assets AS assets
FROM --platform=$TARGETPLATFORM m.daocloud.io/docker.io/library/nginx:${VER_NGX}
LABEL MAINTAINER="ylb<contact@yanglibin.info>"
COPY --from=assets /app/assets /usr/share/nginx/html
